routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\HomeController;
use League\CommonMark\Block\Element\Document;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', [LoginController::class, 'showLoginForm'])->name('auth.login');


Route::group(['middleware' => ['role:Regional Director']], function () {
  Route::prefix('admin')->name('admin.')->group(function () {

    //Regional Director  = Admin
    // Routes for user managemnet 
    Route::get('/user', [HomeController::class, 'users'])->name('showUser');
    Route::get('/adduser', [HomeController::class, 'showAddUser'])->name('addUser');
    Route::post('/saveaccount', [HomeController::class, 'add'])->name('saveaccount');
    Route::get('/edit/{id}', [HomeController::class, 'showEdit'])->name('editUser');
    Route::post('/saveEdit/{id}', [HomeController::class, 'update'])->name('update');
    Route::post('/savedelete/{id}', [HomeController::class, 'delete'])->name('accountdelete');

    // routes for Document Management - Reginal Director
    Route::get('/dashboard', [DocumentController::class, 'adminDashboard'])->name('dashboard');
    Route::get('/display', 'DocumentController@displayunrouted')->name('documents');
    Route::get('/routed', 'DocumentController@displayrouted')->name('routed');
    Route::get('/{action}/{id}/{rid}/', 'DocumentController@view')->name('recordview');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('delete');

    //myprofile
    Route::get('/myprofile/{id}', [UserController::class, 'showEdit'])->name('profile');

    //commments
    Route::get('/displaycomments', [DocumentController::class, 'displaycomments'])->name('displaycomments');

    //document receive
    Route::get('/displaydocumentreceive', [DocumentController::class, 'displaydocumentreceive'])->name('displaydocumentreceive');
    Route::get('/displaydocumentunreceive', [DocumentController::class, 'displaydocumentunreceive'])->name('displaydocumentunreceive');

    //actions settings
    Route::get('/actions', [DocumentController::class, 'actionsettings'])->name('actions');
    Route::post('/saveaction', [DocumentController::class, 'saveaction']);
    Route::post('/updateaction/{id}', [DocumentController::class, 'updateaction'])->name('updateaction');
    Route::post('/deleteaction/{id}', [DocumentController::class, 'deleteaction'])->name('deleteaction');

    //document types
    Route::get('/types', [DocumentController::class, 'documenttypes'])->name('types');
    Route::post('/savedoctype', [DocumentController::class, 'savedoctype']);
    Route::post('/updatedocumenttype/{id}', [DocumentController::class, 'updatedocumenttype'])->name('updatedocumenttype');
  });
});


// User routes
Route::group(['middleware' => ['role:Document Controller']], function () {
  Route::prefix('user')->name('user.')->group(function () {
    //mydocuments tab
    Route::get('/newdocument', 'DocumentController@newDocView')->name('incoming_doc');
  });
});

Route::group(['middleware' => ['permission:view-incoming-documents']], function () {
  Route::prefix('admin')->name('admin.')->group(function () {
    Route::post('/document', 'DocumentController@saveRecord')->name('savedoc');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('edit');
    Route::post('/saveupdate/{id}', 'DocumentController@editRecord')->name('saveupdate');
    Route::get('/download/{file}', 'DocumentController@getDownload')->name('download');
  });
});


Route::group(['middleware' => ['role:Document Controller|Division Head|Section Head|Ordinary User Role']], function () {
  Route::prefix('user')->name('user.')->group(function () {
    //dashboard tab
    Route::get('/dashboard', [DocumentController::class, 'userDashboard'])->name('dashboard');

    //recent document
    Route::get('/mydocs', [DocumentController::class, 'showDocuments'])->name('document');
    Route::get('/{action}/{id}/{rid}/', 'DocumentController@view')->name('recordview');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('edit');
    Route::post('/received/{id}', [DocumentController::class, 'received'])->name('received');
    Route::get('/download/{file}', 'DocumentController@getDownload')->name('download');

    //pending document - ordinary user/heads
    Route::get('/pendingdoc', [DocumentController::class, 'pendingDocuments'])->name('pending');
    Route::get('/pendingIncomingDocuments', [DocumentController::class, 'pendingIncomingDocuments'])->name('pendingincoming');

    //received document
    Route::get('/receiveddoc', [DocumentController::class, 'receivedDocuments'])->name('receive');

    //routed to me
    Route::get('/routedocument', 'DocumentController@showRoutedDoc')->name('routings');

    //myprofile
    Route::get('/myprofile/{id}', [UserController::class, 'showEdit'])->name('profile');
    Route::post('/update/{id}', [UserController::class, 'update'])->name('update');
  });
});

//for testings
Route::get('/', [UserController::class, 'try']);

//route for underdevelopment page
Route::get('/underdevelpoment', [HomeController::class, 'underdevelopment']);




// C:/xampp/htdocs/DTS/dts
// Auth::routes();
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/about.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet" href="{{ mix('css/app.css') }}" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous"/>
</head>
<body class="bg-white text-dark">
    <header class="c-header c-header-light px-3">
        <ul class="c-header-nav ">
            <li class="c-header-nav-item ">
                <a class="c-header-brand text-decoration-none" href="{{ route('auth.login') }}">
                    <h3 class="pt-2">TRACE</h3>
                </a>
            </li>
        </ul>    

        <ul class="c-header-nav ml-auto mr-3">
        <li class="c-header-nav-item mr-4">
            <a class="c-header-nav-link " href="{{ route('contact') }}">Contact Info <span class="sr-only">(current)</span></a>
        </li>
        <li class="c-header-nav-item mr-4 active">
            <a class="c-header-nav-link font-weight-bold" >About Us</a>
        </li>
        <li class="c-header-nav-item">
            <a class="c-header-nav-link " href="{{ route('auth.login') }}">Login</a>
        </li>
        </ul>
    </header>

    <div class="container-fluid align-items-center fade-in">
        <h1 class="text-center  mt-5 mb-5 " style=" color: #212121;">ABOUT US</h1>
        <div class="" style="width: 45%; height: 300px; margin: 80px 0px 0px 60px;">
            <div class=" ">

            </div>
            <div class="p-5" style="color: #212121;">
                <h3 class="text-center">Document Tracking Sytem (DTS)</h3>
                <p class="mt-4 text-justify">Document Tracking System (DTS) is an information system capable of tracking the paper trail of documents created within office 
                    of company/organization. The DTS includes information on the originating and receiving office and personnel, as well as the time elapsed between offices/units/departments. 
                    In this information system, document attachments, revisions, updates, and remarks are also supported.
                    
                </p>
            </div>
        </div>
        <div class="" style="width: 45%; height: 300px; float: right; margin: -300px 60px 0px 0px;">
            <div class="">

            </div>
            <div class="p-5" style="color: #212121;">
                 <h3 class="text-center">Department of Science and Technology (DOST XI) </h3>
                <p class="mt-4 text-justify">
                    DOST XI provides technology training services to customers particularly those intending to establish new technology-based enterprises (livelihood) or upgrade existing ones. 
                    This program involves the transfer of knowledge and/or skills by tapping S&T experts from various RDIs and councils thru any or a combination of the following processes:
                </p>
            </div>
        </div>
    </div>
</body>
    <div class="container" style="margin-top: 80px;">
        <div class="p-2">
             <div class="c-footer bg-white" style="padding-left: 39%;">
                 Copyright &copy; {{ date('Y') }} &nbsp;
                <a href="https://region11.dost.gov.ph" class="text-decoration-none"> DOSTrack</a>, All rights reserved
            </div>
           
        </div>  
        
    </div>
    <div class="container text-center " style="color:#616161;">
            Developer: Steven C. Badang - 2021
    </div> 
    <div class="container text-center " style="color:#616161;">
            Developer: Remi Vallejo - 2022
    </div> 
</html>

resources/views/comments.blade.php
@extends('layouts.app')
@section('after-styles')
    <link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
<div class="container-fluid">
    <div class="fade-in">
            <nav aria-label="breadcrumb" >
                <ol class="breadcrumb" style="font-size: 16px;">
                    <li class="breadcrumb-item">View Comments</li>
                </ol>
            </nav> 

        <div class="card">
            <div class="card-body">
                <div class="justify-content-between">
                    <div class="container mt-5">
                        <table class="table table-bordered yajra-datatable">
                                <thead>
                                    <tr>
                                    <th scope="col">Subject</th>
                                    <th scope="col">Comment</th>
                                    <th scope="col">Commented by</th>
                                    <th scope="col">Document Receive</th>
                                    <th scope="col">Action</th>
                                    </tr>
                                </thead>

                            <tbody>
                            @foreach ($documents as $documents)
                            <tr>
                                <td>{{ $documents->subject }}</td>
                                <td>{{ $documents->route_to_message }}</td>
                                <td>{{ $documents->route_to_name }}</td>
                                <td>{{ $documents->updated_at }}</td>
                                <td class="action">
                                        <a class="" href="/admin/retrieve/{{ $documents->doc_id }}/{{ $documents->route_id }}" >
                                            <button type="button" class="btn btn-success btn-sm">
                                                <span class="cil-description btn-icon mr-1"></span>View
                                            </button>
                                        </a>  
                                </td>
                            </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
               
            </div>
        </div>
        
    </div>
</div>
@endsection
@section('after-scripts')
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
$(function () {
    var table = $('.yajra-datatable').DataTable({
        "order": [[5, "desc"]]
    });

});
   
</script>
@endsection

resources/views/edit.blade.php
@extends('layouts.app')

@section('after-styles')
    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.js"></script>
@endsection

@section('content')
<link rel="stylesheet" href="{{asset('css/style.css')}}">
<div class="container-fluid mb-3">
    @role('Regional Director')
        <div class="fade-in">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="font-size: 16px;">
                    <li class="breadcrumb-item"><a href="{{ route('admin.documents')}}" class="breadcrumb-item"  aria-current="page">View Documents</a></li>
                    <li class="breadcrumb-item active">Tag</li>
                </ol>
            </nav>  
        </div>
    @endrole
    @role('Document Controller')
        <div class="fade-in">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="font-size: 16px;">
                    <li class="breadcrumb-item"><a href="{{ route('user.incoming_doc')}}" class="breadcrumb-item"  aria-current="page">Incoming Document</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('user.document')}}" class="breadcrumb-item"  aria-current="page">View Documents</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </nav>  
        </div>
    @endrole
    @role('Ordinary User Role|Section Head|Division Head')
        <div class="fade-in">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="font-size: 16px;">
                    <li class="breadcrumb-item"><a href="{{ route('user.document')}}" class="breadcrumb-item"  aria-current="page">View Documents</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </nav>  
        </div>
    @endrole
    
     @foreach ($document as $document)
    <!-- The form -->
    
    
    
    <form action="{{ route('admin.saveupdate', $document->doc_id)}}" method="post" enctype="multipart/form-data" class="myform">
        {{ csrf_field()}}
        <div class="shadow bg-white " style="padding: 20px 150px 20px 100px; margin: 0px 0px 0px 10px;" id="div-form" >
                {{-- <h3 style="text-align: center; margin: 10px 0px 30px 0px;">Edit Document's Data</h3> --}}
                <h5 class="heading" style="margin: 0px 0px 0px 70px;">Document Information </h5>
                <div class="form-group row "  style="margin-top: 50px;">
                    <input type="text" value="{{ $document->doc_id }}" name="doc_id" hidden>
                    <label for="subject" class="col-sm-2 col-form-label"  style="text-align: right" >Subject:</label>
                    <div class="col-sm-10">
                    <input type="text" class="form-control" id="subject" name="subject" autocomplete="on" value="{{ $document->subject }}"required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="docType" class="col-sm-2 col-form-label" style="text-align: right" >Document Type:</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="doc_type">
                            <option value="{{  $document->document_type }}" hidden>{{ $document->document_type}}</option>
                            @foreach ($doc_types as $doc_type)
                                <option value="{{ $doc_type->doc_type }}">{{$doc_type->doc_type}}</option>
                            @endforeach
                            
                        </select>
                    </div>
                </div>
                

                <div class="form-group row">
                <label for="docDate" class="col-sm-2 col-form-label" style="text-align: right">Document Date:</label>
                    <div class="col-sm-10" style=" width: 245px;" >
                    <input type="date" class="form-control" id="docDate" style="width: 250px;" name="doc_date" autocomplete="off"  value="{{ $document->document_date }}"required >
                    </div>
                </div>

                <div class="form-group row">
                    <label for="date-received" class="col-sm-2 col-form-label" style="text-align: right">Date Received:</label>
                    <div class="col-sm-10" style=" width: 245px;" >
                        <input type="date" class="form-control" id="date-received"  style="width: 250px;" name="date_received" autocomplete="off" value="{{ $document->date_received }}"required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="sender" class="col-sm-2 col-form-label" style="text-align: right">Sender:</label>
                    <div class="col-sm-10" style=" width: 245px;" >
                        <input type="text" class="form-control" id="sender" name="sender" autocomplete="on" value="{{ $document->sender }}" required >
                    </div>
                </div>

                <div class="form-group row">
                <label for="company_desc" class="col-sm-2 col-form-label" style="text-align: right">Company:</label>
                    <div class="col-sm-10" style=" width: 245px;" >
                        <input type="text" class="form-control" id="company_desc" name="company" autocomplete="on" value="{{ $document->company }}"required >
                    </div>
                </div>

                <h5 class="heading" style="margin: 80px 0px 0px 70px;">File Attachments</h5>
                <div class="form-group row" style="margin: 20px 0px 30px 90px;" >
                    <div class="col-sm-10">
                        <?php  
                            $fileArr = DB::table('attachments_lists')
                                    ->select('file_name') 
                                    ->where('doc_id', $document->doc_id)
                                    ->get();
                             
                        ?>
                        @foreach($fileArr as $file)
                                <input type="text" name="oldFile[]"  value="{{ $file->file_name }}" hidden >
                                <a href="{{ route('admin.download',$file->file_name)}}" class="active" data-toggle="tooltip" data-placement="bottom" title="Click to download" >{{ $file->file_name }}</a>
                        @endforeach
                    </div>
                </div>

                <div class="form-group row">
                <label for="files" class="col-sm-2 col-form-label" style="text-align: right">Replace Attachment:</label>
                    <div class="col-sm-10" style=" width: 245px;" >
                        <input type="file" class="border  @error('file') is-invalid @enderror" id="file" name="file[]" multiple >
                        @if(Session::get('fail'))
                                <div class="alert text-danger">
                                    {{ Session::get('fail')}}
                                </div>
                        @endif
                    </div>
                     
                </div>
                 
               
                    <h5 class="heading" style="margin: 80px 0px 0px 70px;">Routing Information</h5>
                <div class="form-group row"  style="margin-top: 50px;" >
                <input type="text" value="{{ $document->route_id }}" name="route_id" hidden>
                <label for="routingSlip" class="col-sm-2 col-form-label"  style="text-align: right">Routing Slip:</label>
                <div class="col-sm-10">
                        <input type="text" class="form-control" id="routingSlip"  value="{{ $document->route_slip }}" name="slip"readonly>
                    </div>
                </div>
                <div class="form-group row">
                                <label for="from" class="col-sm-2 col-form-label" style="text-align: right">From:</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="from" name="rfrom" required value="{{ $document->route_from }}">
                                </div>
                </div>

                @if (auth()->user()->usergroup == "Regional Director")
                <div class="form-group row"  style="margin-top: 20px;" >
                    <label for="route-thru" class="col-sm-2 col-form-label required"  style="text-align: right" required >Routed Thru:</label>
                    <div class="col-sm-10">
                        <select class="form-control"  name="routeThru[]" id="choices-multiple-remove-button" placeholder="{{$document->route_thru}}" value="{{$document->route_thru}}" multiple>
                             @foreach ($heads as $user)
                                <option value="{{$user->fname . " " .  $user->lname}}">{{$user->fname . " ". $user->lname . " (". $user->usergroup .") "}} </option>
                            @endforeach
                        </select> 
                    </div>
                </div>

                <div class="form-group row"  style="margin-top: 20px;" >
                <label for="route-to" class="col-sm-2 col-form-label required"  style="text-align: right" required >Routed To:</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="routeTo[]" id="choices-multiple-remove-button" placeholder="{{ $document->route_to }}" value="{{ $document->route_to }}" multiple>
                                @foreach ($ordinary as $user)
                                    <option value="{{$user->fname . " " .  $user->lname}}">{{$user->fname . " ". $user->lname}}</option>
                                @endforeach
                        </select> 
                    </div>
                </div>
       
                <div class="form-group row"  style="margin-bottom: 60px;">
                <label for="action" class="col-sm-2 col-form-label required"  style="text-align: right" required >Action Needed:</label>
                
                <div class="col-sm-10">
                    <select class="form-control" name="action[]" id="choices-multiple-remove-button" placeholder="{{ $document->action }}" value="{{ $document->action }}"  multiple>
                        @foreach ($actions as $action)
                            <option value="{{$action->action}}" >{{$action->action}}</option>    
                        @endforeach
                    </select>
                </div>
                </div>
                @endif
                

            <div class="form-group row "  >
                <div class="col-lg ">
                    @role('Regional Director')
                        <button type="submit" class="btn btn-primary" style="width: 150px; height: 45px; margin-left:16px; float: right;">Tag</button>
                        <a href="{{ route('admin.documents') }}" ><button type="button" class="btn btn-secondary" style="width: 150px; height: 45px; float: right;">Back</button></a>
                    @endrole
                    @role('Document Controller|Division Head|Section Head|Ordinary User Role')
                        <button type="submit" class="btn btn-primary" style="width: 150px; height: 45px; margin-left:16px; float: right;">Update</button>
                        <a href="{{ route('user.document') }}" ><button type="button" class="btn btn-secondary" style="width: 150px; height: 45px; float: right;">Back</button></a>
                    @endrole
                </div>
            </div>
           
             
        </div>
        @endforeach
                
    </form>
                    
</div>
<script>
  $(document).ready(function(){
    
     var multipleCancelButton = new Choices('#choices-multiple-remove-button', {
        removeItemButton: true,
        
        searchResultLimit:5,
        
      }); 
     
     
 });
</script>
@endsection

resources/views/recordview.blade.php
@extends('layouts.app')

@section('after-styles')
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
<div class="container-fluid" >
    <!-- fade-in -->
     @role('Regional Director')
        <div class="fade-in">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="font-size: 16px;">
                    <li class="breadcrumb-item"><a href="{{ route('admin.documents')}}" class="breadcrumb-item"  aria-current="page">View Documents</a></li>
                    <li class="breadcrumb-item" aria-current="page">Record's Information</li>
                </ol>
            </nav>  
        </div>
    @endrole
  


    @foreach($document as $document)
    <div class="form-group fade-in p-3 mb-5 bg-white"  style="margin: 20px 0px 0px 0px; width: auto;" >
      <form action="{{route('user.received', $document->doc_id)}}" method="POST" style="padding: 20px 200px 20px 200px;">
        @csrf
        <h3 style="margin: 20px 0px 80px 250px;">Document's Information</h3>
            <div class="form-group row">
                <div class="col">
                    <label for="subject">Subject</label>
                    <input type="text" class="form-control bg-white border-dark" id="subject" value="{{ $document->subject }}" readonly>
                </div>
                <div class="col">
                    <label for="type">Document Type</label>
                    <input type="text" class="form-control  bg-white border-dark" id="type" value="{{ $document->document_type }}" readonly>
                </div>
            </div>
            <div class="form-group row">
                <div class="col">
                    <label for="subject">Document Date</label>
                    <input type="text" class="form-control  bg-white border-dark" id="subject" value="{{ $document->document_date }}" readonly>
                </div>
                <div class="col">
                    <label for="type">Date Received</label>
                    <input type="text" class="form-control  bg-white border-dark" id="type" value="{{ $document->date_received }}" readonly>
                </div>
            </div>
            <div class="form-group row">
                <div class="col">
                    <label for="subject">Sender</label>
                    <input type="text" class="form-control  bg-white border-dark" id="subject"  value="{{ $document->sender }}" readonly>
                </div>
                <div class="col">
                    <label for="type">Company</label>
                    <input type="text" class="form-control  bg-white border-dark" id="type"  value="{{ $document->company }}" readonly>
                </div>
            </div>
            <div class="form-group row" style="margin-top: 80px;">
            <div class="col">
                    <label for="subject">Routing Slip</label>
                    <input type="text" class="form-control  bg-white border-dark" id="subject" value="{{ $document->route_slip }}" readonly>
                </div>
                <div class="col">
                    <label for="type">Routed Thru</label>
                    <input type="text" class="form-control  bg-white border-dark" id="type" value="{{ $document->route_thru }}" readonly>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-lg-6">
                    <label for="subject">Routing To</label>
                    <input type="text" class="form-control  bg-white border-dark" id="subject"value="{{ $document->route_to }}"  readonly>
                </div>
                <div class="col-lg-6">
                    <label for="subject">Action Needed</label>
                    <input type="text" class="form-control  bg-white border-dark" id="subject" style="margin: 0px 0px 50px 0px;" value="{{ $document->action }}"  readonly>
                </div>
                <div class="col">
                        <p>File Attachments</p>
                        <?php  
                            $fileArr = DB::table('attachments_lists')
                                    ->select('file_name') 
                                    ->where('doc_id', $document->doc_id)
                                    ->get();
                             
                        ?>
                        @foreach($fileArr as $file)
                                <input type="text" name="oldFile[]"  value="{{ $file->file_name }}" hidden >
                                <a href="{{ route('admin.download',$file->file_name)}}" class="active" data-toggle="tooltip" data-placement="bottom" title="Click to download" >{{ $file->file_name }}</a>
                        @endforeach
                    </div>
                    {{-- To be fix --}}
                    {{-- @role('Regional Director')
                        @foreach ($comments as $object)    
                            <div class="col">
                                    <label for="exampleFormControlTextarea1" class="form-label">Comments</label>
                                    <textarea class="form-control" name="comments" placeholder="{{ $object->route_to_message }}" value="{{ $object->route_to_message }}" id="exampleFormControlTextarea1" rows="3"></textarea>
                            </div>
                        @endforeach
                    @endrole --}}
                    @if(auth()->user()->usergroup == 'Ordinary User' || auth()->user()->usergroup == "Section Head" || auth()->user()->usergroup == "Division Head" || auth()->user()->usergroup == "Document Controller") 
                        @foreach ($comments as $object)    
                            <div class="col">
                                <label for="exampleFormControlTextarea1" class="form-label">Comments</label>
                                <textarea class="form-control" name="comments" placeholder="{{ $object->route_to_message }}" value="{{ $object->route_to_message }}" id="exampleFormControlTextarea1" rows="3"></textarea>
                            </div>
            </div>
                    {{-- receive--}}
                            @if($object->receive == 'no')
                            <div class="form-group row">
                                    <div class="col">
                                                <button type="submit" class="btn btn-success" style="width: 150px; height: 45px; float: right;">Receive Document</button>
                                    </div>
                            </div> 
                            @endif
                        @endforeach            
                    @endif
        </form>
        
    </div>
    @endforeach
</div>
@endsection