routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\HomeController;
use League\CommonMark\Block\Element\Document;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', [LoginController::class, 'showLoginForm'])->name('auth.login');


Route::group(['middleware' => ['role:Regional Director']], function () {
  Route::prefix('admin')->name('admin.')->group(function () {

    //Regional Director  = Admin
    // Routes for user managemnet 
    Route::get('/user', [HomeController::class, 'users'])->name('showUser');
    Route::get('/adduser', [HomeController::class, 'showAddUser'])->name('addUser');
    Route::post('/saveaccount', [HomeController::class, 'add'])->name('saveaccount');
    Route::get('/edit/{id}', [HomeController::class, 'showEdit'])->name('editUser');
    Route::post('/saveEdit/{id}', [HomeController::class, 'update'])->name('update');
    Route::post('/savedelete/{id}', [HomeController::class, 'delete'])->name('accountdelete');

    // routes for Document Management - Reginal Director
    Route::get('/dashboard', [DocumentController::class, 'adminDashboard'])->name('dashboard');
    Route::get('/display', 'DocumentController@displayunrouted')->name('documents');
    Route::get('/routed', 'DocumentController@displayrouted')->name('routed');
    Route::get('/{action}/{id}/{rid}/', 'DocumentController@view')->name('recordview');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('delete');

    //myprofile
    Route::get('/myprofile/{id}', [UserController::class, 'showEdit'])->name('profile');

    //commments
    Route::get('/displaycomments', [DocumentController::class, 'displaycomments'])->name('displaycomments');

    //document receive
    Route::get('/displaydocumentreceive', [DocumentController::class, 'displaydocumentreceive'])->name('displaydocumentreceive');
    Route::get('/displaydocumentunreceive', [DocumentController::class, 'displaydocumentunreceive'])->name('displaydocumentunreceive');

    //actions settings
    Route::get('/actions', [DocumentController::class, 'actionsettings'])->name('actions');
    Route::post('/saveaction', [DocumentController::class, 'saveaction']);
    Route::post('/updateaction/{id}', [DocumentController::class, 'updateaction'])->name('updateaction');
    Route::post('/deleteaction/{id}', [DocumentController::class, 'deleteaction'])->name('deleteaction');

    //document types
    Route::get('/types', [DocumentController::class, 'documenttypes'])->name('types');
    Route::post('/savedoctype', [DocumentController::class, 'savedoctype']);
    Route::post('/updatedocumenttype/{id}', [DocumentController::class, 'updatedocumenttype'])->name('updatedocumenttype');
  });
});


// User routes
Route::group(['middleware' => ['role:Document Controller']], function () {
  Route::prefix('user')->name('user.')->group(function () {
    //mydocuments tab
    Route::get('/newdocument', 'DocumentController@newDocView')->name('incoming_doc');
  });
});

Route::group(['middleware' => ['permission:view-incoming-documents']], function () {
  Route::prefix('admin')->name('admin.')->group(function () {
    Route::post('/document', 'DocumentController@saveRecord')->name('savedoc');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('edit');
    Route::post('/saveupdate/{id}', 'DocumentController@editRecord')->name('saveupdate');
    Route::get('/download/{file}', 'DocumentController@getDownload')->name('download');
  });
});


Route::group(['middleware' => ['role:Document Controller|Division Head|Section Head|Ordinary User Role']], function () {
  Route::prefix('user')->name('user.')->group(function () {
    //dashboard tab
    Route::get('/dashboard', [DocumentController::class, 'userDashboard'])->name('dashboard');

    //recent document
    Route::get('/mydocs', [DocumentController::class, 'showDocuments'])->name('document');
    Route::get('/{action}/{id}/{rid}/', 'DocumentController@view')->name('recordview');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('edit');
    Route::post('/received/{id}', [DocumentController::class, 'received'])->name('received');
    Route::get('/download/{file}', 'DocumentController@getDownload')->name('download');

    //pending document - ordinary user/heads
    Route::get('/pendingdoc', [DocumentController::class, 'pendingDocuments'])->name('pending');
    Route::get('/pendingIncomingDocuments', [DocumentController::class, 'pendingIncomingDocuments'])->name('pendingincoming');

    //received document
    Route::get('/receiveddoc', [DocumentController::class, 'receivedDocuments'])->name('receive');

    //routed to me
    Route::get('/routedocument', 'DocumentController@showRoutedDoc')->name('routings');

    //myprofile
    Route::get('/myprofile/{id}', [UserController::class, 'showEdit'])->name('profile');
    Route::post('/update/{id}', [UserController::class, 'update'])->name('update');
  });
});

//for testings
Route::get('/', [UserController::class, 'try']);

//route for underdevelopment page
Route::get('/underdevelpoment', [HomeController::class, 'underdevelopment']);




// C:/xampp/htdocs/DTS/dts
// Auth::routes();
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/addUser.blade.php
@extends('layouts.app')
@section('after-styles')
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
<div class="container-fluid">
    <div class="fade-in">
      

        <div class="conatiner" >
            <div class="card-body bg-white border mb-5" style="width: 700px; margin: 50px 0px 0px 25%;">
            <div  class="card-body" >
                <h2 class="mb-5 text-center">Create User Account</h2>
                <form method="post" action="{{ route('admin.saveaccount') }}" style="width: 500px; display: inline-block; margin-left: 10%;" >
                @csrf
                    @if(Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ Session::get('success')}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                    @endif
                    @if(Session::get('fail'))
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ Session::get('fail')}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                    @endif
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="cil-user"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control @error('firstname') is-invalid @enderror"
                            name="firstname" value="{{ old('firstname') }}"placeholder="First Name">
                        @error('firstname')
                            <div class="invalid-feedback">{{ $message }}</div>
                         @enderror
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="cil-user"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control @error('lastname') is-invalid @enderror"
                            name="lastname" value="{{ old('firstname') }}"placeholder="Last Name">
                        @error('lastname')
                            <div class="invalid-feedback">{{ $message }}</div>
                         @enderror
                    </div>
                     <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="cil-envelope-open"></i>
                            </span>
                        </div>
                        <input type="email" class="form-control @error('email') is-invalid @enderror"
                            name="email" value="{{ old('email') }}"placeholder="Email">
                        @error('email')
                            <div class="invalid-feedback">{{ $message }}</div>
                         @enderror
                    </div>
                     <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="cil-lock-locked"></i>
                            </span>
                        </div>
                        <input type="password" class="form-control @error('password') is-invalid @enderror"
                            name="password" placeholder="Password">
                        @error('password')
                            <div class="invalid-feedback">{{ $message }}</div>
                         @enderror
                    </div>
                    <div class="input-group mb-3"  style="margin-bottom: 60px;">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="cil-people"></i>
                            </span>
                        </div>

                        <select class="form-control" id="action" name="usergroup">
                            <option value="Regional Director">Regional Director</option>
                            <option value="Division Head">Division Head</option>
                            <option value="Section Head">Section Head</option>
                            <option value="Document Controller">Document Controller</option>
                            <option value="Ordinary User">Ordinary User</option>
                        </select>
                        @error('usergroup')
                            <div class="invalid-feedback">{{ $message }}</div>
                         @enderror
                    </div>
                    <input type="submit" class="btn btn-primary" style="float: right">
                    <a href="{{ route('admin.showUser') }}"><button type="button" class="btn btn-secondary" style="float: right; margin-right: 20px;">Cancel</button></a>
                </form>
            </div>
            </div>
        </div>
   

</div>
    


@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.app')
@section('after-styles')
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

@endsection
@section('content')

            <div class="container-fluid fade-in ">
                <div class="row d-flex justify-content-center">
                    <div class="col-sm-5 col-lg-4">
                        <div class="card shadow">
                            <div class="card-header bg-youtube content-center text-uppercase large text-white">
                                <i class="c-header-nav "></i> Documents
                            </div>
                            <div class="card-body row text-center">
                                <div class="col">
                                    <div class="text-value-xl">{{count($routedocuments) + count($documents)}}</div>
                                    <div class="text-uppercase text-muted small">Incoming documents</div>
                                </div>
                                <div class="c-vr"></div>
                                <div class="col">
                                    <a href="{{ route('admin.routed')}}" class="text-value-xl text-dark">{{ count($routedocuments)}}</a>
                                    <div class="text-uppercase text-muted small">Routed Documents</div>
                                </div>
                            </div>
                        </div>
                    </div>
                 <div class="col-lg-4">
                    <div class="card shadow">
                        <div class="card-header bg-yahoo content-center text-uppercase large text-white">
                           <i class="c-header-nav "></i> Notifications
                        </div>
                        <div class="card-body row text-center">
                            <div class="col">
                                <a href="{{ route('admin.displaycomments')}}" class="text-value-xl text-dark">{{ count($comments)}}</a>
                                <div class="text-uppercase text-muted small">Comments</div>
                            </div>
                            <div class="c-vr"></div>
                            <div class="col">
                                <a href="{{ route('admin.documents')}}" class="text-value-xl text-dark">{{ count($documents)}}</a>
                                <div class="text-uppercase text-muted small">pending documents</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-6">
                    <div class="card mb-4 shadow">
                        <div class="card-header text-center">
                            <i class="fas fa-chart-area me-1"></i>
                                        <Strong>Documents Added Per Day</Strong>
                            </div>
                        <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                    </div>
                </div>
            <div class="col-xl-6">
                <div class="card mb-4 shadow">
                    <div class="card-header text-center">
                            <i class="fas fa-chart-bar me-1"></i>
                                        <Strong>Documents Added Per Month</Strong>
                    </div>
                    <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="card mb-4 shadow">
                    <div class="card-header text-center">
                            <i class="fas fa-chart-bar me-1"></i>
                                        <Strong>Received Documents vs Unreceived Documents</Strong>
                    </div>
                    <div class="card-body"><canvas id="myPieChart" width="100%" height="40"></canvas></div>
                </div>
            </div>
        </div>
        </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script type="text/javascript">
    var _ydata = JSON.parse('{!! json_encode($months) !!}');
    var _xdata = JSON.parse('{!! json_encode($monthCount) !!}');

    var _yddata = JSON.parse('{!! json_encode($dmonths) !!}');
    var _xddata = JSON.parse('{!! json_encode($dmonthCount) !!}');

    var _xpie  = JSON.parse('{!! json_encode($_xpie) !!}');
</script>
<script src="{{asset('assets/demo/chart-area-demo.js')}}"></script>
<script src="{{asset('assets/demo/chart-bar-demo.js')}}"></script>
<script src="{{asset('assets/demo/chart-pie-demo.js')}}"></script>
</div>
@endsection


@section('after-scripts')
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script> $(function () { var table = $('.yajra-datatable').DataTable(); }); </script>

@endsection

resources/views/admin/editUser.blade.php
@extends('layouts.app')
@section('after-styles')
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
<div class="container-fluid">
    <div class="fade-in">
       

    <div class="fade-in">
        <div class="conatiner" >
            <div class="card-body bg-white border mb-5 " style="width: 700px; margin: 50px 0px 0px 25%;">
                <div class="card-body mb-4" >
                    <h2 class="mb-5 text-center">Edit User Account</h2>
                     @foreach($user as $users)
                    <form action="/admin/saveEdit/{{ $users->id }}" method="post">
                        @csrf
                        <div class="form-group row "  >
                            <label for="subject" class="col-sm-2 col-form-label"  style="text-align: right" >Firstname:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="fname" name="fname" autocomplete="on" value="{{ $users->fname }}"required>
                            </div>
                        </div>
                        
                        <div class="form-group row "  >
                            <label for="subject" class="col-sm-2 col-form-label"  style="text-align: right" >Lastname:</label>
                            <div class="col-sm-10 ">
                                <input type="text" class="form-control  " id="lname" name="lname" autocomplete="on" value="{{ $users->lname }}"required>
                            </div>
                        </div>
                        <div class="form-group row "  >
                            <label for="subject" class="col-sm-2 col-form-label"  style="text-align: right" >Email:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="email" name="email" autocomplete="on" 
                                value="{{ $users->email }}"required>
                                
                            </div>
                            
                        </div>
                        <div class="form-group row"  >
                            <label for="subject" class="col-sm-2 col-form-label"  style="text-align: right" >Group:</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="usergroup" id="usergroup"> 
                                    <option value="{{$users->usergroup}}" selected disabled>{{$users->usergroup}}</option>
                                    <option value="Regional Director">Regional Director</option>
                                    <option value="Division Head">Division Head</option>
                                    <option value="Section Head">Section Head</option>
                                    <option value="Document Controller">Document Controller</option>
                                    <option value="Ordinary User">Ordinary User</option>
                                </select>
                            </div>
                        </div>
                        {{-- <div class="form-group row"  >
                            <label for="subject" class="col-sm-2 col-form-label"  style="text-align: right" >Role:</label>
                            <div class="col-sm-10">
                                @foreach($userole as $role)
                                <select class="form-control" id="role" name="role" style="width: 150px;">
                                    <option value="admin" <?php if($role->role_id == '2' ) {echo("selected");}?> >Administrator</option>
                                    <option value="staff" <?php if($role->role_id == '1') {echo("selected");}?> >Staff</option>
                                </select>
                                @endforeach
                            </div>
                        </div> --}}
                        @endforeach
                        <button type="submit" class="btn btn-primary" style="float: right">Update</button>
                        <a href="{{ route('admin.showUser') }}" style="float: right; margin-right: 10px;"><button type="button" class="btn btn-primary">Cancel</button></a>
                    </form>
                </div>
            </div>
        </div>
    </div>
   

</div>
    


@endsection

resources/views/admin/user.blade.php
@extends('layouts.app')
@section('after-styles')
    <link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
   
    <div class="container-fluid" style="font-size: 16px;">
        <div class="fade-in">
            @role('Regional Director')
                <div class="card-title" style="margin-top: 40px;"><a class="btn btn-success " href="{{ route('admin.addUser') }}" style="float:right;">Create</a></div>
            @endrole
            <h2 class="card-title" >User Accounts</h2> 
    
             <div class="card">
                <div class="card-body">
                    <div class="flex">
                        <div class="container-fluid mt-5">
                            <table class="table table-bordered yajra-datatable" >
                            <!-- yajra-datatable -->
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Firstname</th>
                                        <th>Lastname</th>
                                        <th>Email</th>
                                        <th>Role</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($user as $users)
                                    <tr>
                                        <td>{{ $users->id }}</td>
                                        <td>{{ $users->fname }}</td>
                                        <td>{{ $users->lname }}</td>
                                        <td>{{ $users->email }}</td>
                                        <td>{{ $users->role }}</td>
                                            <td>
                                                <a class="btn btn-info btn-sm" href="/admin/edit/{{ $users->id }}" ><span class="cil-pencil btn-icon mr-1"></span>Edit</a>
                                                <a class="btn btn-danger btn-sm" href="" data-toggle="modal" data-target="#exampleModal{{ $users->id }}"><span class="cil-remove btn-icon mr-1"></span>Delete</a>
                                            </td>
                                    </tr>
                                    
                                    <!-- The Modal -->
                                    <div class="modal fade" id="exampleModal{{ $users->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <form action="{{ route('admin.accountdelete',$users->id)}}" method="post">
                                    @csrf
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <strong><p>User: {{ $users->fname }}</p></strong>
                                                <strong><p>Role: {{ $users->role }}</p></strong>
                                                <p>Are you sure you want to delete this record?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                    </form>
                                    </div>
                                    @endforeach
                            </tbody>
                            </table>
                        </div>

                    </div> 
                </div>
            </div>
        </div>
    </div>
    
@endsection
@section('after-scripts')
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
$(function () {
    var table = $('.yajra-datatable').DataTable();
    table.page( 'next' ).draw( true );
});
   
</script>
@endsection