routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\HomeController;
use League\CommonMark\Block\Element\Document;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', [LoginController::class, 'showLoginForm'])->name('auth.login');


Route::group(['middleware' => ['role:Regional Director']], function () {
  Route::prefix('admin')->name('admin.')->group(function () {

    //Regional Director  = Admin
    // Routes for user managemnet 
    Route::get('/user', [HomeController::class, 'users'])->name('showUser');
    Route::get('/adduser', [HomeController::class, 'showAddUser'])->name('addUser');
    Route::post('/saveaccount', [HomeController::class, 'add'])->name('saveaccount');
    Route::get('/edit/{id}', [HomeController::class, 'showEdit'])->name('editUser');
    Route::post('/saveEdit/{id}', [HomeController::class, 'update'])->name('update');
    Route::post('/savedelete/{id}', [HomeController::class, 'delete'])->name('accountdelete');

    // routes for Document Management - Reginal Director
    Route::get('/dashboard', [DocumentController::class, 'adminDashboard'])->name('dashboard');
    Route::get('/display', 'DocumentController@displayunrouted')->name('documents');
    Route::get('/routed', 'DocumentController@displayrouted')->name('routed');
    Route::get('/{action}/{id}/{rid}/', 'DocumentController@view')->name('recordview');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('delete');

    //myprofile
    Route::get('/myprofile/{id}', [UserController::class, 'showEdit'])->name('profile');

    //commments
    Route::get('/displaycomments', [DocumentController::class, 'displaycomments'])->name('displaycomments');

    //document receive
    Route::get('/displaydocumentreceive', [DocumentController::class, 'displaydocumentreceive'])->name('displaydocumentreceive');
    Route::get('/displaydocumentunreceive', [DocumentController::class, 'displaydocumentunreceive'])->name('displaydocumentunreceive');

    //actions settings
    Route::get('/actions', [DocumentController::class, 'actionsettings'])->name('actions');
    Route::post('/saveaction', [DocumentController::class, 'saveaction']);
    Route::post('/updateaction/{id}', [DocumentController::class, 'updateaction'])->name('updateaction');
    Route::post('/deleteaction/{id}', [DocumentController::class, 'deleteaction'])->name('deleteaction');

    //document types
    Route::get('/types', [DocumentController::class, 'documenttypes'])->name('types');
    Route::post('/savedoctype', [DocumentController::class, 'savedoctype']);
    Route::post('/updatedocumenttype/{id}', [DocumentController::class, 'updatedocumenttype'])->name('updatedocumenttype');
  });
});


// User routes
Route::group(['middleware' => ['role:Document Controller']], function () {
  Route::prefix('user')->name('user.')->group(function () {
    //mydocuments tab
    Route::get('/newdocument', 'DocumentController@newDocView')->name('incoming_doc');
  });
});

Route::group(['middleware' => ['permission:view-incoming-documents']], function () {
  Route::prefix('admin')->name('admin.')->group(function () {
    Route::post('/document', 'DocumentController@saveRecord')->name('savedoc');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('edit');
    Route::post('/saveupdate/{id}', 'DocumentController@editRecord')->name('saveupdate');
    Route::get('/download/{file}', 'DocumentController@getDownload')->name('download');
  });
});


Route::group(['middleware' => ['role:Document Controller|Division Head|Section Head|Ordinary User Role']], function () {
  Route::prefix('user')->name('user.')->group(function () {
    //dashboard tab
    Route::get('/dashboard', [DocumentController::class, 'userDashboard'])->name('dashboard');

    //recent document
    Route::get('/mydocs', [DocumentController::class, 'showDocuments'])->name('document');
    Route::get('/{action}/{id}/{rid}/', 'DocumentController@view')->name('recordview');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('edit');
    Route::post('/received/{id}', [DocumentController::class, 'received'])->name('received');
    Route::get('/download/{file}', 'DocumentController@getDownload')->name('download');

    //pending document - ordinary user/heads
    Route::get('/pendingdoc', [DocumentController::class, 'pendingDocuments'])->name('pending');
    Route::get('/pendingIncomingDocuments', [DocumentController::class, 'pendingIncomingDocuments'])->name('pendingincoming');

    //received document
    Route::get('/receiveddoc', [DocumentController::class, 'receivedDocuments'])->name('receive');

    //routed to me
    Route::get('/routedocument', 'DocumentController@showRoutedDoc')->name('routings');

    //myprofile
    Route::get('/myprofile/{id}', [UserController::class, 'showEdit'])->name('profile');
    Route::post('/update/{id}', [UserController::class, 'update'])->name('update');
  });
});

//for testings
Route::get('/', [UserController::class, 'try']);

//route for underdevelopment page
Route::get('/underdevelpoment', [HomeController::class, 'underdevelopment']);




// C:/xampp/htdocs/DTS/dts
// Auth::routes();
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\RoleRelationship;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable, HasRoles;
    protected $connection = 'mysql';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fname',
        'lname',
        'email',
        'password',
        'birthday',
        'phone',
        'picture',
        'usergroup'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',

    ];


    public static function role()
    {
        return $this->belongsToMany('App\Role');
    }
}

app/Models/users.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Traits\HasRoles;

class users extends Model
{
    use HasFactory;

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Auth\Access\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{

    // ------------------------------- User Management Controls -------------------------------------------------

    public function showProfile()
    {
        $id = auth()->user()->id;
        $user_info = DB::table('users')
            ->select('users.*')
            ->where('id', $id)
            ->get();

        return view('user.profile', compact('user_info'));
    }
    public function showEdit($id)
    {
        $user_info = DB::table('users')
            ->select('users.*')
            ->where('id', $id)
            ->get();

        return view('user.profile', compact('user_info'));
    }
    public function try()
    {
        $ordinary = DB::table('users')
            ->select('users.fname', 'users.lname')
            ->where('usergroup', '=', 'Ordinary User')
            ->get();
        $heads = DB::table('users')
            ->select('users.fname', 'users.lname', 'usergroup')
            ->where('usergroup', '<>', 'Ordinary User')
            ->where('usergroup', '<>', 'Document Controller')
            ->where('usergroup', '<>', 'Regional Director')
            ->get();
        $actions = DB::table('actions')
            ->get();

        $doc_types = DB::table('document_types')
            ->get();
        $document = DB::table('document_details')
            ->join('routing_details', 'document_details.route_id', '=', 'routing_details.route_id')
            ->where('document_details.doc_id', '182')
            ->get();


        return view('try', compact('document', 'ordinary', 'heads', 'actions', 'doc_types'));
    }
    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $formfields = $request->validate([
            'fname' => 'required',
            'lname' => 'required',
            'email' => 'required'
        ]);

        $formfields['birthday'] = $request->birthday;
        $formfields['phone'] = $request->phone;

        if ($request->hasFile('picture')) {
            $formfields['picture'] = $request->file('picture')->getClientOriginalName();
            $request->file('picture')->move(public_path("/uploads"), $request->file('picture')->getClientOriginalName());
        }
        $user->update($formfields);

        return redirect('user/myprofile/' . $id);
    }

    public function pendingDocumentsOrdinary()
    {
        $document = DB::table('document_details')
            ->join(
                'routing_details',
                'document_details.route_id',
                '=',
                'routing_details.route_id'
            )
            ->where('routing_details.route_to', '=', auth()->user()->fname . " " . auth()->user()->lname)
            ->get();

        return view('user.document', compact('document'));
    }
    public function ret(Request $request, $action, $doc_id, $route_id)
    {
        $document = DB::table('document_details')
            ->join('routing_details', 'document_details.route_id', '=', 'routing_details.route_id')
            ->where('document_details.doc_id', $doc_id)
            ->get();

        if ($action == "edit") {
            return View("edit", compact('document'));
        } else if ($action == "delete") {
            DB::delete('delete from attachments_lists where doc_id = ?', [$doc_id]);
            DB::delete('delete from document_details where doc_id = ?', [$doc_id]);
            DB::delete('delete from routing_details where route_id = ?', [$route_id]);
            return redirect('user/mydocs');
        } else if ($action == "retrieve") {
            return View("recordview", compact('document'));
        } else {
            return View("view", compact('document'));
        }
    }
}

resources/views/user/dashboard.blade.php
@extends('layouts.app')
@section('after-styles')
    <link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
<div class="container-fluid ">
    <div class="fade-in">
        @role('Document Controller')
         <div class="row justify-content-center">
                <div class="col-lg-4">
                    <div class="card shadow">
                        <div class="card-header bg-youtube content-center text-uppercase large text-white">
                            <i class="c-header-nav "></i> Documents
                        </div>
                        <div class="card-body row text-center">
                            <div class="col">
                                {{-- correct output --}}
                                <a href="{{ route('user.document')}}" class="text-value-xl text-dark"> {{count($document)}}</a>
                                <div class="text-uppercase text-muted small">Incoming documents</div>
                            </div>
                            <div class="c-vr"></div>
                            <div class="col">
                                <div class="text-value-xl">{{ count($document) - count($pending)}}</div>
                                <div class="text-uppercase text-muted small">Routed Documents</div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-4">
                     <div class="card shadow">
                        <div class="card-header bg-yahoo content-center text-uppercase large text-white">
                           <i class="c-header-nav "></i> Notifications
                        </div>
                        <div class="card-body row text-center">
                            <div class="col">
                                <div class="text-value-xl">0</div>
                                <div class="text-uppercase text-muted small">Messages</div>
                            </div>
                            <div class="c-vr"></div>
                            <div class="col">
                                
                                <a href="{{ route('user.pendingincoming')}}" class="text-value-xl text-dark"> {{count($pending)}}</a>
                                <div class="text-uppercase text-muted small">unrouted documents</div>
                            </div>
                        </div>
                    </div>
                </div>
           </div>
        @endrole
        @role('Ordinary User Role|Division Head|Section Head')
           <div class="row justify-content-center">
                <div class="col-sm-5 col-lg-4 ">
                    <div class="card shadow">
                        <div class="card-header bg-youtube content-center text-uppercase large text-white">
                            <i class="c-header-nav "></i> Documents
                        </div>
                        <div class="card-body row text-center">
                            <div class="col">
                                <div class="text-value-xl">{{ count($document) }}</div>
                                <div class="text-uppercase text-muted small">Incoming documents</div>
                            </div>
                            <div class="c-vr"></div>
                            <div class="col">
                                <a href="{{ route('user.receive')}}" class="text-value-xl text-dark"> {{count($document) - count($pendings)}}</a>
                                <div class="text-uppercase text-muted small">recieved documents</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-5 col-lg-4 ">
                    <div class="card shadow">
                        <div class="card-header bg-yahoo content-center text-uppercase large text-white">
                           <i class="c-header-nav "></i> Notifications
                        </div>
                        <div class="card-body row text-center">
                            <div class="col">
                                <div class="text-value-xl">0</div>
                                <div class="text-uppercase text-muted small">Messages</div>
                            </div>
                            <div class="c-vr"></div>
                            <div class="col">
                                <a href="{{ route('user.pending')}}" class="text-value-xl text-dark"> {{count($pendings)}}</a>
                                <div class="text-uppercase text-muted small">Pending documents</div>
                            </div>
                        </div>
                    </div>
                </div>
           </div>
        @endrole
    </div>
</div>
<div class="container-fluid">
     <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card p-5 shadow">
                    <p class="h5">Welcome {{ auth()->user()->fname }}! </p>
                    <p>You now have access to DOST XI TRACE DTS Management System.</p>
                    <div class="card-body">
                    </div>
                </div>
        </div>
     </div>
</div>
@endsection
@section('after-scripts')
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
$(function () {
    var table = $('.yajra-datatable').DataTable();
});
   
</script>
@endsection

resources/views/user/document.blade.php
@extends('layouts.app')
@section('after-styles')
    <link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
<div class="container-fluid">
    {{-- if user is document holder --}}
    
    @if( auth()->user()->usergroup == "Document Controller")
        
        @role('Document Controller')
        <nav aria-label="breadcrumb" >
            <ol class="breadcrumb" style="font-size: 16px;">
                <li class="breadcrumb-item active"><a href="{{ route('user.incoming_doc') }}" class="breadcrumb-item "  aria-current="page">Incoming Document</a></li>
                <li class="breadcrumb-item active">View documents</li>
            </ol>
        </nav> 
        @endrole
        @role('admin')
        <nav aria-label="breadcrumb" >
            <ol class="breadcrumb" style="font-size: 16px;">
                <li class="breadcrumb-item active">Incoming Document</li>
                <li class="breadcrumb-item"><a href="{{ route('admin.documents') }}" class="breadcrumb-item "  aria-current="page">View Documents</a></li>
            </ol>
        </nav> 
        @endrole
    @endif
       
    <div class="fade-in">
        
        <h2 class="mb-4 text-center">My Documents</h2>
        <div class="card rounded" style="width: 80%; margin-left: 12%;">
            <div class="card-body mb-4">
                    @if(Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ Session::get('success')}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                    @endif
                    <div class="container mt-5">
                       <table class="table border yajra-datatable hover">
                                <thead class="text-value-md">
                                    <tr>
                                        <th scope="col" class="border-top-0 border-bottom-0 text-nowrap">No</th>
                                        <th scope="col" class="border-top-0 border-bottom-0 text-nowrap">Subject</th>
                                        <th scope="col" class="border-top-0 border-bottom-0 text-nowrap">Document Type</th>
                                        <th scope="col" class="border-top-0 border-bottom-0 text-nowrap">Sender</th>
                                        <th scope="col" class="border-top-0 border-bottom-0 text-nowrap">Company</th>
                                        <th scope="col" class="border-top-0 border-bottom-0 text-nowrap">Action</th>
                                    </tr>
                                </thead>

                            <tbody>
                            @foreach ($document as $documents)
                            <tr>
                                <td>{{ $documents->doc_id }}</td>
                                <td>{{ $documents->subject }}</td>
                                <td>{{ $documents->document_type }}</td>
                                <td>{{ $documents->sender }}</td>
                                <td>{{ $documents->company }}</td>
                                <td class="action">
                                    
                                    @if (auth()->user()->usergroup == "Ordinary User" || auth()->user()->usergroup == "Section Head" || auth()->user()->usergroup == "Division Head")
                                        <a class="" href="/user/retrieve/{{ $documents->doc_id }}/{{ $documents->route_id }}" ><button type="button" class="btn btn-success btn-sm"><span class="cil-description btn-icon mr-1"></span>View</button></a>                                   
                                    @else
                                        <a class="" href="/user/retrieve/{{ $documents->doc_id }}/{{ $documents->route_id }}" ><button type="button" class="btn btn-success btn-sm"><span class="cil-description btn-icon mr-1"></span>View</button></a>                                   
                                        <a class="" href="/user/edit/{{ $documents->doc_id }}/{{ $documents->route_id }}" ><button type="button" class="btn btn-info btn-sm"><span class="cil-pencil btn-icon mr-1"></span>Edit</button></a>
                                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal{{ $documents->doc_id }}"><span class="cil-remove btn-icon mr-1"></span>Delete</button>
                                    @endif
                                </td>
                            </tr>
                    

                                <!-- The Modal -->
                                <div class="modal fade" id="exampleModal{{ $documents->doc_id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to delete this record?</p>
                                        <p>doc_id:{{ $documents->doc_id }} </p>
                                        <p>route_id: {{ $documents->route_id }}</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                                        <input type="text" value="{{ $documents->route_id }}" name = "doc_id" hidden >
                                        <a href="/admin/delete/{{$documents->doc_id}}/{{$documents->route_id}}"><button type="button" class="btn btn-danger">Delete</button></a>
                                    </div>
                                    </div>
                                </div>
                                </div>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
               
            </div>
        </div>
        
    </div>
</div>
@endsection

@section('after-scripts')
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
$(function () {
    var table = $('.yajra-datatable').DataTable();
});
    // var Chart = Chart;
    
    // var Chart = Chart.BarController;
    // console.log(Chart);
    // Chart.register(Chart);
    var ctx = document.getElementById('myChart');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
            datasets: [{
                label: '# of Votes',
                data: [12, 19, 3, 5, 2, 3],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
    </script>
@endsection

resources/views/user/profile.blade.php
@extends('layouts.app')
@section('after-styles')
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection

@section('content')

<div class="container fade-in">
   
<form action="/user/update/{{auth()->user()->id}}" method="post" enctype="multipart/form-data">
    @csrf
    @foreach($user_info as $user)
    <div class="container-fluid mt-4" style="width: 700px;">
        
            <div class="form-group row d-flex align-items-center justify-content-center ">
               <img src="{{$user->picture ? asset('uploads/'.$user->picture) : asset('img/circle-user-regular.svg')}}" alt="picture" class="w-25 h-25 border" style="border-radius: 50%" > 
            </div>
    <div class="accordion" id="accordionExample">
        <div class="card">
              
            <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                    <button class="btn " type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <h6>Basic Information</h6>
                    </button>
                </h2>
            </div>
            
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="container">
                        <div class="form-group row" >
                            <label for="rto" class="col-sm-2 col-form-label" style="text-align: right">Firstname:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="rto" value="{{ $user->fname }}"name="fname" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="rto" class="col-sm-2 col-form-label" style="text-align: right">Lastname:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="rto" value="{{ $user->lname }}" name="lname" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="rto" class="col-sm-2 col-form-label" style="text-align: right">Birthday:</label>
                            <div class="col-sm-10">
                                <input type="date" class="form-control" id="rto" value="{{$user->birthday}}" name="birthday">
                            </div>
                        </div>
                         <div class="form-group row">
                            <label for="rto" class="col-sm-2 col-form-label" style="text-align: right">Picture</label>
                            <div class="col-sm-10">
                                 <input type="file" class="form-control p-1" id="rto" name="picture">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="pos" class="col-sm-2 col-form-label" style="text-align: right">Position:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="pos" value="{{$user->usergroup}}" name="position"  readonly>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        
        <div class="card">
            <div class="card-header" id="headingTwo">
                <h2 class="mb-0">
                    <button class="btn collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    <h6>Contact Information</h6>
                    </button>
                </h2>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body">

                <div class="container">
                    <div class="form-group row" >
                        <label for="rto" class="col-sm-2 col-form-label" style="text-align: right">Email:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="rto"  value="{{ $user->email }}"  name="email" required>
                        </div>
                    </div>
                   
                    <div class="form-group row">
                        <label for="rto" class="col-sm-2 col-form-label" style="text-align: right">Phone:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="rto" name="phone" value="{{ $user->phone }}" >
                        </div>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>
    </div>
    
    
    @endforeach

    <div class="container-fluid mb-3" style="width: 700px;">
        <button class="btn btn-block btn-primary mb-5">Update</button>
    </div>
</form>
</div>
    



@endsection