routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\HomeController;
use League\CommonMark\Block\Element\Document;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', [LoginController::class, 'showLoginForm'])->name('auth.login');


Route::group(['middleware' => ['role:Regional Director']], function () {
  Route::prefix('admin')->name('admin.')->group(function () {

    //Regional Director  = Admin
    // Routes for user managemnet 
    Route::get('/user', [HomeController::class, 'users'])->name('showUser');
    Route::get('/adduser', [HomeController::class, 'showAddUser'])->name('addUser');
    Route::post('/saveaccount', [HomeController::class, 'add'])->name('saveaccount');
    Route::get('/edit/{id}', [HomeController::class, 'showEdit'])->name('editUser');
    Route::post('/saveEdit/{id}', [HomeController::class, 'update'])->name('update');
    Route::post('/savedelete/{id}', [HomeController::class, 'delete'])->name('accountdelete');

    // routes for Document Management - Reginal Director
    Route::get('/dashboard', [DocumentController::class, 'adminDashboard'])->name('dashboard');
    Route::get('/display', 'DocumentController@displayunrouted')->name('documents');
    Route::get('/routed', 'DocumentController@displayrouted')->name('routed');
    Route::get('/{action}/{id}/{rid}/', 'DocumentController@view')->name('recordview');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('delete');

    //myprofile
    Route::get('/myprofile/{id}', [UserController::class, 'showEdit'])->name('profile');

    //commments
    Route::get('/displaycomments', [DocumentController::class, 'displaycomments'])->name('displaycomments');

    //document receive
    Route::get('/displaydocumentreceive', [DocumentController::class, 'displaydocumentreceive'])->name('displaydocumentreceive');
    Route::get('/displaydocumentunreceive', [DocumentController::class, 'displaydocumentunreceive'])->name('displaydocumentunreceive');

    //actions settings
    Route::get('/actions', [DocumentController::class, 'actionsettings'])->name('actions');
    Route::post('/saveaction', [DocumentController::class, 'saveaction']);
    Route::post('/updateaction/{id}', [DocumentController::class, 'updateaction'])->name('updateaction');
    Route::post('/deleteaction/{id}', [DocumentController::class, 'deleteaction'])->name('deleteaction');

    //document types
    Route::get('/types', [DocumentController::class, 'documenttypes'])->name('types');
    Route::post('/savedoctype', [DocumentController::class, 'savedoctype']);
    Route::post('/updatedocumenttype/{id}', [DocumentController::class, 'updatedocumenttype'])->name('updatedocumenttype');
  });
});


// User routes
Route::group(['middleware' => ['role:Document Controller']], function () {
  Route::prefix('user')->name('user.')->group(function () {
    //mydocuments tab
    Route::get('/newdocument', 'DocumentController@newDocView')->name('incoming_doc');
  });
});

Route::group(['middleware' => ['permission:view-incoming-documents']], function () {
  Route::prefix('admin')->name('admin.')->group(function () {
    Route::post('/document', 'DocumentController@saveRecord')->name('savedoc');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('edit');
    Route::post('/saveupdate/{id}', 'DocumentController@editRecord')->name('saveupdate');
    Route::get('/download/{file}', 'DocumentController@getDownload')->name('download');
  });
});


Route::group(['middleware' => ['role:Document Controller|Division Head|Section Head|Ordinary User Role']], function () {
  Route::prefix('user')->name('user.')->group(function () {
    //dashboard tab
    Route::get('/dashboard', [DocumentController::class, 'userDashboard'])->name('dashboard');

    //recent document
    Route::get('/mydocs', [DocumentController::class, 'showDocuments'])->name('document');
    Route::get('/{action}/{id}/{rid}/', 'DocumentController@view')->name('recordview');
    Route::get('/{action}/{id}/{rid}', 'DocumentController@view')->name('edit');
    Route::post('/received/{id}', [DocumentController::class, 'received'])->name('received');
    Route::get('/download/{file}', 'DocumentController@getDownload')->name('download');

    //pending document - ordinary user/heads
    Route::get('/pendingdoc', [DocumentController::class, 'pendingDocuments'])->name('pending');
    Route::get('/pendingIncomingDocuments', [DocumentController::class, 'pendingIncomingDocuments'])->name('pendingincoming');

    //received document
    Route::get('/receiveddoc', [DocumentController::class, 'receivedDocuments'])->name('receive');

    //routed to me
    Route::get('/routedocument', 'DocumentController@showRoutedDoc')->name('routings');

    //myprofile
    Route::get('/myprofile/{id}', [UserController::class, 'showEdit'])->name('profile');
    Route::post('/update/{id}', [UserController::class, 'update'])->name('update');
  });
});

//for testings
Route::get('/', [UserController::class, 'try']);

//route for underdevelopment page
Route::get('/underdevelpoment', [HomeController::class, 'underdevelopment']);




// C:/xampp/htdocs/DTS/dts
// Auth::routes();
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/includes/footer.blade.php
<footer class="c-footer">
    <div>
        Copyright &copy; {{ date('Y') }}
        <a href="https://region11.dost.gov.ph">  DOSTrack</a>, All rights reserved
        {{-- © 2020 creativeLabs. --}}
    </div>
    <!-- <div class="ml-auto"><a href="https://region11.dost.gov.ph/">DOST XI </a> | Developed by ICT Section | Powered by&nbsp;<a href="https://coreui.io/">CoreUI</a></div> -->
</footer>

resources/views/includes/header.blade.php
<header class="c-header c-header-dark c-header-fixed c-header-with-subheader">
    <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
        <i class="c-icon c-icon-lg cil-menu"></i>
    </button>

    <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
        <i class="c-icon c-icon-lg cil-menu"></i>
      
    </button>

    <ul class="c-header-nav d-md-down-none" >
        <h3><li class="c-header-nav-item px-3" > <a class="c-header-nav-link " href="{{ route('admin.dashboard') }}">TRACE</a> </li></h3>

        <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">&nbsp;</a></li>
        <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">&nbsp;</a></li>
        <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">&nbsp;</a></li>
    </ul>

    <ul class="c-header-nav ml-auto mr-4">
       
        <li class="c-header-nav-item dropdown">
            <a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <div class="c-avatar"><img class="c-avatar-img" src="{{(auth()->user()->picture != null) ? asset('uploads/'.auth()->user()->picture) : asset ('profile/no-user-photo.png')}}" alt="user@email.com" style="width:40px; height: 35px"></div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
                @role('Regional Director')
                <a class="dropdown-item" href="/admin/myprofile/{{auth()->user()->id}}">
                   <i class="c-sidebar-nav-icon fa-solid fa-user"></i> My Profile
                </a>
                <a class="dropdown-item" href="{{ route('admin.actions')}}">
                   <i class="c-sidebar-nav-icon c-sidebar-nav-icon fa-solid fa-gear"></i> Action Settings
                </a>
                 <a class="dropdown-item" href="{{ route('admin.types') }}">
                   <i class="c-sidebar-nav-icon fa-regular fa-file"></i> Document Types
                </a>
                @endrole
                <a class="dropdown-item" href="{{ route('auth.logout') }}">
                   <i class="c-sidebar-nav-icon cil-account-logout"></i> Logout
                </a>
            </div>
        </li>
    </ul>
   
</header>

resources/views/includes/sidebar.blade.php
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar" style="font-size: 16px;">
    <div class="c-sidebar-brand d-lg-down-none">
       
    </div>
    <ul class="c-sidebar-nav ps">
        <li class="c-sidebar-nav-item">
            <!-- checking the roles of the currently logged in user  -->
            @role('Regional Director')
                <a class="c-sidebar-nav-link" href="{{url('admin/dashboard')}}">
            @endrole
            @role('Document Controller|Ordinary User Role|Division Head|Section Head')
                <a class="c-sidebar-nav-link" href="{{url('user/dashboard')}}">
            @endrole
                    <i class="c-sidebar-nav-icon fa-solid fa-gauge"></i>Dashboard
                </a>
        </li>
        
        <!-- sidebar for administrators  -->
        @role('Regional Director')
        <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
            <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#docs">
                <i class="c-sidebar-nav-icon fa-solid fa-file"></i>Documents
            </a>
            @if (auth()->user()->usergroup == "Regional Director")
            <ul class="c-sidebar-nav-dropdown-items">
                <li class="c-sidebar-nav-item text-value-md">
                    <a class="c-sidebar-nav-link " href="{{ route('admin.documents')}}" style="font-size: 15px;">
                         <i class="c-sidebar-nav-icon cil-address-book"></i> Pending Documents
                    </a>
                </li>
                 <li class="c-sidebar-nav-item text-value-md">
                    <a class="c-sidebar-nav-link " href="{{ route('admin.routed')}}" style="font-size: 15px;">
                        <i class="c-sidebar-nav-icon cil-map"></i> Routed Document 
                    </a>
                </li>
                 <li class="c-sidebar-nav-item text-value-md">
                    <a class="c-sidebar-nav-link " href="{{ route('admin.displaydocumentreceive') }}" style="font-size: 15px;">
                        <i class="c-sidebar-nav-icon fa-solid fa-file-circle-check"></i> Received Document 
                    </a>
                </li>
            </ul>
            @endif
        </li>
       
        <li class="c-sidebar-nav-item" >
            
            <a href="{{ route('admin.showUser') }}" class="c-sidebar-nav-link"><i class="c-sidebar-nav-icon fa-solid fa-users"></i>Users</a>
        </li>
        <li class="c-sidebar-nav-item" >
            <a href="/underdevelpoment" class="c-sidebar-nav-link"><i class="c-sidebar-nav-icon fa-solid fa-arrow-trend-up"></i>Statistics</a>
        </li>
        <li class="c-sidebar-nav-item" >
            <a href="/underdevelpoment" class="c-sidebar-nav-link"><i class="c-sidebar-nav-icon fa-solid fa-user-group"></i>Employees</a>
        </li>
       
        @endrole

        

        <!-- sidebar for staffs eg doc con or ordinary users  -->
        @role('Document Controller')
       
            @if (auth()->user()->usergroup == "Document Controller")
             <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#docs">
                    <i class="c-sidebar-nav-icon fa-solid fa-file"></i>Documents
                </a>
                        <ul class="c-sidebar-nav-dropdown-items">
                            <li class="c-sidebar-nav-item">
                                <a class="c-sidebar-nav-link " href="{{ route('user.incoming_doc') }}" style="font-size: 15px;">
                                    <i class="c-sidebar-nav-icon fa-solid fa-right-from-bracket"></i> Incoming Document
                                    
                                </a>
                            </li>
                        </ul>
                        <ul class="c-sidebar-nav-dropdown-items">
                            <li class="c-sidebar-nav-item">
                                <a class="c-sidebar-nav-link " href="{{ route('user.document') }}" style="font-size: 15px;">
                                    <i class="c-sidebar-nav-icon fa-solid fa-file-circle-check"></i> Recent Document
                                </a>
                            </li>
                        </ul>
                         
             </li>
            @endif
             <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
            <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#notif">
                <i class="c-sidebar-nav-icon fa-solid fa-bell"></i>Notifications
            </a>
            <ul class="c-sidebar-nav-dropdown-items text-value-md">
                <li class="c-sidebar-nav-items text-value-md">
                    <a class="c-sidebar-nav-link" href="/underdevelpoment">
                        <i class="c-sidebar-nav-icon cil-envelope-closed"></i> Messages
                    </a>
                </li>
            </ul>
            <ul class="c-sidebar-nav-dropdown-items">
                            <li class="c-sidebar-nav-item">
                                <a class="c-sidebar-nav-link text-value-md" href="{{ route('user.pending') }}">
                                    <i class="c-sidebar-nav-icon cil-address-book"></i> Pending Documents
                                </a>
                            </li>
            </ul>

            {{-- <ul class="c-sidebar-nav-dropdown-items">
                <li class="c-sidebar-nav-item text-value-md">
                    <a class="c-sidebar-nav-link " href="/underdevelpoment">
                        <i class="c-sidebar-nav-icon cil-library"></i> Routed to Me
                    </a>
                </li>
            </ul> --}}

            <li class="c-sidebar-nav-item" >
                <a href="/user/myprofile/{{auth()->user()->id}}" class="c-sidebar-nav-link">
                <i class="c-sidebar-nav-icon fa-solid fa-user"></i></i>My Profile</a>
            </li>

        </li> 
        @endrole
        @role('Ordinary User Role|Division Head|Section Head')
            
            @if (auth()->user()->usergroup == "Division Head" || auth()->user()->usergroup == "Ordinary User" || auth()->user()->usergroup == "Section Head" )
            <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#docs">
                    <i class="c-sidebar-nav-icon fa-solid fa-file"></i>Documents
                </a>
                 <ul class="c-sidebar-nav-dropdown-items">
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link text-value-md" href="{{ route('user.pending') }}">
                            <i class="c-sidebar-nav-icon cil-address-book"></i> Pending Documents
                        </a>
                    </li>
                </ul>
                <ul class="c-sidebar-nav-dropdown-items">
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link text-value-md" href="{{route('user.receive')}}">
                            <i class="c-sidebar-nav-icon cil-check-circle"></i> Received Documents
                        </a>
                    </li>
                </ul>
            </li>
        
            @endif
             <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
            <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#notif">
                <i class="c-sidebar-nav-icon fa-solid fa-bell"></i>Notifications
            </a>
            <ul class="c-sidebar-nav-dropdown-items text-value-md">
                <li class="c-sidebar-nav-items text-value-md">
                    <a class="c-sidebar-nav-link" href="/underdevelpoment">
                        <i class="c-sidebar-nav-icon cil-envelope-closed"></i> Messages
                    </a>
                </li>
            </ul>

            {{-- <ul class="c-sidebar-nav-dropdown-items">
                <li class="c-sidebar-nav-item text-value-md">
                    <a class="c-sidebar-nav-link " href="/underdevelpoment">
                        <i class="c-sidebar-nav-icon cil-library"></i> Routed to Me
                    </a>
                </li>
            </ul> --}}

            <li class="c-sidebar-nav-item" >
                <a href="/user/myprofile/{{auth()->user()->id}}" class="c-sidebar-nav-link">
                <i class="c-sidebar-nav-icon fa-solid fa-user"></i></i>My Profile</a>
            </li>

        </li> 
        @endrole
        <div class="ps__rail-x" style="left: 0px; bottom: 0px;">
            <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
        </div>
        <div class="ps__rail-y" style="top: 0px; right: 0px;">
            <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div>
        </div>
    </ul>
    <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
</div>